### PR TITLE
Add ansible playbook for installing and running ArangoDB on AWS EC2 instance

### PR DESCRIPTION
**Pull request by waxlamp**

### CODE REVIEW

**Comment by JackWilb** [comment]
Do we want to add a github actions yaml along with this?

**Comment by waxlamp** [comment]
> Do we want to add a github actions yaml along with this?

To automatically update a running server? Probably not. This playbook is so simple as to be something that we could just run by hand when needed. (That reminds me that I need to add some documentation about how this is used.)

**Comment by JackWilb** [comment]
> > Do we want to add a github actions yaml along with this?
> 
> To automatically update a running server? Probably not. This playbook is so simple as to be something that we could just run by hand when needed. (That reminds me that I need to add some documentation about how this is used.)

Will that be on this PR? If not, it's ready to go.

**Comment by waxlamp** [comment]
> > > Do we want to add a github actions yaml along with this?
> > 
> > 
> > To automatically update a running server? Probably not. This playbook is so simple as to be something that we could just run by hand when needed. (That reminds me that I need to add some documentation about how this is used.)
> 
> Will that be on this PR? If not, it's ready to go.

I've got a general, self-assigned task to improve documentation. So, probably not on this PR.

**Pull request merged**
